from src.tasks.sql_task import SQLTask


SALES_SCHEMA = """
CREATE TABLE customers (
    customer_id INTEGER PRIMARY KEY,
    customer_name TEXT,
    region TEXT
);

CREATE TABLE orders (
    order_id INTEGER PRIMARY KEY,
    customer_id INTEGER,
    order_date TEXT,
    product TEXT,
    quantity INTEGER,
    unit_price REAL,
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
);
"""


SALES_DATABASE = """
CREATE TABLE customers (
    customer_id INTEGER PRIMARY KEY,
    customer_name TEXT,
    region TEXT
);

CREATE TABLE orders (
    order_id INTEGER PRIMARY KEY,
    customer_id INTEGER,
    order_date TEXT,
    product TEXT,
    quantity INTEGER,
    unit_price REAL,
    FOREIGN KEY (customer_id) REFERENCES customers(customer_id)
);

INSERT INTO customers VALUES
    (1, 'Alice', 'North'),
    (2, 'Bob', 'South'),
    (3, 'Carol', 'North'),
    (4, 'David', 'East'),
    (5, 'Emma', 'South');

INSERT INTO orders VALUES
    (101, 1, '2026-01-10', 'Laptop', 2, 1200.00),
    (102, 1, '2026-01-15', 'Mouse', 5, 25.00),
    (103, 2, '2026-02-05', 'Laptop', 1, 1200.00),
    (104, 3, '2026-02-12', 'Keyboard', 3, 80.00),
    (105, 4, '2026-02-20', 'Monitor', 2, 300.00),
    (106, 5, '2026-03-01', 'Mouse', 10, 25.00),
    (107, 2, '2026-03-10', 'Monitor', 1, 300.00),
    (108, 3, '2026-03-15', 'Laptop', 1, 1200.00);
"""


SQL_TASKS = [
    SQLTask(
        question="What is the total revenue generated by each product?",
        schema=SALES_SCHEMA,
        database_sql=SALES_DATABASE,
        reference_sql="""
            SELECT product, SUM(quantity * unit_price)
            FROM orders
            GROUP BY product
        """,
    ),
    SQLTask(
        question="How many orders were placed by customers in each region?",
        schema=SALES_SCHEMA,
        database_sql=SALES_DATABASE,
        reference_sql="""
            SELECT c.region, COUNT(o.order_id)
            FROM customers c
            JOIN orders o ON c.customer_id = o.customer_id
            GROUP BY c.region
        """,
    ),
    SQLTask(
        question="What is the average order value?",
        schema=SALES_SCHEMA,
        database_sql=SALES_DATABASE,
        reference_sql="""
            SELECT AVG(quantity * unit_price)
            FROM orders
        """,
    ),
    SQLTask(
        question="Which product generated the highest total revenue?",
        schema=SALES_SCHEMA,
        database_sql=SALES_DATABASE,
        reference_sql="""
            SELECT product
            FROM orders
            GROUP BY product
            ORDER BY SUM(quantity * unit_price) DESC
            LIMIT 1
        """,
    ),
    SQLTask(
        question="What is the total revenue generated by each region?",
        schema=SALES_SCHEMA,
        database_sql=SALES_DATABASE,
        reference_sql="""
            SELECT c.region, SUM(o.quantity * o.unit_price)
            FROM customers c
            JOIN orders o ON c.customer_id = o.customer_id
            GROUP BY c.region
        """,
    ),
]